version: '3.9'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./virtualvinyl:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
