FROM python:3.10-slim
WORKDIR /app
COPY requirements.frontend.txt requirements.frontend.txt
RUN pip install --no-cache-dir -r requirements.frontend.txt
COPY dash_app.py dash_app.py
EXPOSE 3000
CMD ["python", "dash_app.py"]
